### ISSUE TITLE
accept empty <publish uri="[uri]" /> in snapshots and deltas

### ISSUE THREAD

**Issue by ties** [NLnetLabs/rpki-rs#137]
As a user I want rpki-rs to accept snaphots and deltas that contain a `<publish>` element that is empty (with self-closing and explicit) because the empty string is valid base64 content (and a valid entry __on__ a manifest and thus should be publishable via RRDP).

My interpretation is that [base64Binary](https://www.w3.org/TR/xmlschema-2/) which [RFC8182](https://tools.ietf.org/html/rfc8182) refers to allows the empty string with this grammar:
```
 Base64Binary  ::=  ((B64S B64S B64S B64S)*
                     ((B64S B64S B64S B64) |
                      (B64S B64S B16S '=') |
                      (B64S B04S '=' #x20? '=')))?

B64S         ::= B64 #x20?

B16S         ::= B16 #x20?

B04S         ::= B04 #x20?

B04         ::=  [AQgw]
B16         ::=  [AEIMQUYcgkosw048]
B64         ::=  [A-Za-z0-9+/] 
```

I tried to play around with this myself in https://github.com/ties/rpki-rs/tree/wip/accept-empty-publish-element but did not arrive at a working solution :fearful:.

**Comment by ties** [comment]
Would it be possible for this to make 0.9?

**Comment by partim** [comment]
This requires some bigger changes to the XML decoder (it needs to be able to peak at the next event), which I would rather not do this late in the release cycle.

**Comment by ties** [comment]
I understand the hesitancy to do this late in the release cycle. I think fallback to rsync minimizes the operational risk and based on that I think it is acceptable to postpone this. However I would still recommend to get this fixed soon.

**Comment by ties** [comment]
Can you give an estimated timeline for this? Making the parser `peek` at the next token is hard but I think this is a real issue for some specific repo content.

**Comment by partim** [comment]
Should be in the next Routinator release.

**Comment by ties** [comment]
Nice!
