### ISSUE TITLE
Add support for ASPA objects

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/rpki-rs#159]
This is still being discussed in the IETF but relatively stable now.

See:
https://datatracker.ietf.org/doc/draft-ietf-sidrops-aspa-profile/
https://datatracker.ietf.org/doc/draft-ietf-sidrops-aspa-verification/

OID is still TBD but asked the WG and authors if an early allocation has been made.

**Comment by partim** [comment]
The initial implementation is now been released. If there’s revisions to the spec, we can open new issues.
