### ISSUE TITLE
CSR Decoder

### ISSUE THREAD

**Issue by fredwlau** [NLnetLabs/rpki-rs#205]
I apologize if this is a dumb question, but is it possible to use this library to decode an already existing CSR? I have read through the documentation and source code multiple times but still can't seem to get a clear logic on how to do this. It seems like this library should be leveraged to create a CSR, and there are helper functions to decode that CSR.

Given an existing PEM encoded CSR, I would like to be able to pull attributes from it. Is this functionality supported?

**Comment by timbru** [comment]
A PEM encoded CSR is essentially this:
```
-----BEGIN CERTIFICATE REQUEST-----
<base64 encoded DER encoded CSR>
-----BEGIN CERTIFICATE REQUEST-----
```

So you can base64 decode the content and let this library parse it.

That said.. this library only supports CSR in the context of RPKI so it may lack support for attributes that you need.
