### ISSUE TITLE
failed to select a version for `ring`.

### ISSUE THREAD

**Issue by Ben-Lichtman** [NLnetLabs/rpki-rs#97]
I'm getting the following error when trying to use this crate alongside rustls:

> error: failed to select a version for `ring`.
>     ... required by package `rpki v0.8.0`
>     ... which is depended on by `[...]`
> versions that meet the requirements `^0.14.6` are: 0.14.6
> 
> the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
> package `ring v0.16.11`
>     ... which is depended on by `rustls v0.17.0`
>     ... which is depended on by `[...]`
> 
> failed to select a version for `ring` which could resolve this conflict

**Comment by Ben-Lichtman** [comment]
Was able to fix the problem by using a github link as dependency. Any chance of a release to bump the version though?

**Comment by partim** [comment]
Funny, enough, I merged #96 a couple hours ago, so master should be there already. I wanna do a bit of cleanup before releasing 0.9.0. Can’t be far away, though.

**Comment by Ben-Lichtman** [comment]
Ah good to know. I'll close the issue since the next release is soon.
